export enum Ball {
    MasterBall = 1,
    UltraBall = 2,
    GreatBall = 3,
    PokeBall = 4,
    SafariBall = 5,
    NetBall = 6,
    DiveBall = 7,
    NestBall = 8,
    RepeatBall = 9,
    TimerBall = 10,
    LuxuryBall = 11,
    PremierBall = 12,
    DuskBall = 13,
    HealBall = 14,
    QuickBall = 15,
    CherishBall = 16,
    LureBall = 449,
    LevelBall = 450,
    MoonBall = 451,
    HeavyBall = 452,
    FastBall = 453,
    FriendBall = 454,
    LoveBall = 455,
    ParkBall = 456,
    SportBall = 457,
    DreamBall = 617,
    BeastBall = 887,
}

export const balls = [
    {
        "id": 1,
        "name": "master-ball",
        "en": "Master Ball",
        "fr": "Master Ball",
        "appearedInGen": 1,
    },
    {
        "id": 2,
        "name": "ultra-ball",
        "en": "Ultra Ball",
        "fr": "Hyper Ball",
        "appearedInGen": 1,
    },
    {
        "id": 3,
        "name": "great-ball",
        "en": "Great Ball",
        "fr": "Super Ball",
        "appearedInGen": 1,
    },
    {
        "id": 4,
        "name": "poke-ball",
        "en": "Poké Ball",
        "fr": "Poké Ball",
        "appearedInGen": 1,
    },
    {
        "id": 5,
        "name": "safari-ball",
        "en": "Safari Ball",
        "fr": "Safari Ball",
        "appearedInGen": 1,
    },
    {
        "id": 6,
        "name": "net-ball",
        "en": "Net Ball",
        "fr": "Filet Ball",
        "appearedInGen": 3,
    },
    {
        "id": 7,
        "name": "dive-ball",
        "en": "Dive Ball",
        "fr": "Scuba Ball",
        "appearedInGen": 3,
    },
    {
        "id": 8,
        "name": "nest-ball",
        "en": "Nest Ball",
        "fr": "Faiblo Ball",
        "appearedInGen": 3,
    },
    {
        "id": 9,
        "name": "repeat-ball",
        "en": "Repeat Ball",
        "fr": "Bis Ball",
        "appearedInGen": 3,
    },
    {
        "id": 10,
        "name": "timer-ball",
        "en": "Timer Ball",
        "fr": "Chrono Ball",
        "appearedInGen": 3,
    },
    {
        "id": 11,
        "name": "luxury-ball",
        "en": "Luxury Ball",
        "fr": "Luxe Ball",
        "appearedInGen": 3,
    },
    {
        "id": 12,
        "name": "premier-ball",
        "en": "Premier Ball",
        "fr": "Honor Ball",
        "appearedInGen": 3,
    },
    {
        "id": 13,
        "name": "dusk-ball",
        "en": "Dusk Ball",
        "fr": "Sombre Ball",
        "appearedInGen": 4,
    },
    {
        "id": 14,
        "name": "heal-ball",
        "en": "Heal Ball",
        "fr": "Soin Ball",
        "appearedInGen": 4,
    },
    {
        "id": 15,
        "name": "quick-ball",
        "en": "Quick Ball",
        "fr": "Rapide Ball",
        "appearedInGen": 4,
    },
    {
        "id": 16,
        "name": "cherish-ball",
        "en": "Cherish Ball",
        "fr": "Mémoire Ball",
        "appearedInGen": 4,
    },
    {
        "id": 449,
        "name": "lure-ball",
        "en": "Lure Ball",
        "fr": "Appât Ball",
        "appearedInGen": 2,
    },
    {
        "id": 450,
        "name": "level-ball",
        "en": "Level Ball",
        "fr": "Niveau Ball",
        "appearedInGen": 2,
    },
    {
        "id": 451,
        "name": "moon-ball",
        "en": "Moon Ball",
        "fr": "Lune Ball",
        "appearedInGen": 2,
    },
    {
        "id": 452,
        "name": "heavy-ball",
        "en": "Heavy Ball",
        "fr": "Masse Ball",
        "appearedInGen": 2,
    },
    {
        "id": 453,
        "name": "fast-ball",
        "en": "Fast Ball",
        "fr": "Speed Ball",
        "appearedInGen": 2,
    },
    {
        "id": 454,
        "name": "friend-ball",
        "en": "Friend Ball",
        "fr": "Copain Ball",
        "appearedInGen": 2,
    },
    {
        "id": 455,
        "name": "love-ball",
        "en": "Love Ball",
        "fr": "Love Ball",
        "appearedInGen": 2,
    },
    {
        "id": 456,
        "name": "park-ball",
        "en": "Park Ball",
        "fr": "Parc Ball",
        "appearedInGen": 2,
    },
    {
        "id": 457,
        "name": "sport-ball",
        "en": "Sport Ball",
        "fr": "Compét' Ball",
        "appearedInGen": 4,
    },
    {
        "id": 617,
        "name": "dream-ball",
        "en": "Dream Ball",
        "fr": "Rêve Ball",
        "appearedInGen": 2,
    },
    {
        "id": 887,
        "name": "beast-ball",
        "en": "Beast Ball",
        "fr": "Ultra Ball",
        "appearedInGen": 7,
    }
]